### ISSUE TITLE
java_motion_tracking_example doesn't compile

### ISSUE THREAD

**Issue by gianmaria** [googlesamples/tango-examples-java#64] opened 2016-04-15 10:51 UTC
hello,

i'm trying to test the examples for the Project Tango tablet, and they all works fine except for two of them: "**java_area_description_example**" and "**java_motion_tracking_example**" both with the same error when trying to upload to the Tango: 
![error](https://cloud.githubusercontent.com/assets/736083/14559134/17e473da-0307-11e6-89d8-c7786470768b.png)

one thing that i noted when importing those two projects is that I wasn't prompted to upgrade to Gradle 2.10.0 as in the others.
 
i'm interested especially in "**java_motion_tracking_example**"

my setup:
Project Tango with Android 4.4.2
Android Studio 2.0
Windows 10 64bit

**Comment by jfschmakeit** [comment] 2016-04-19 07:18
I have seen the same issue.

As a workaround for now you can remove the dependency on the local jar library for now. (in `java_motion_tracking_example/app/build.gradle` comment out the line `compile fileTree(dir: external_lib_prefix + '/jar', include: ['**/*.jar'])`.
The issue is that the same jar is pulled in twice, once from the util module and the app module.

I believe the java_area_description_example is broken too with the same error.

**Comment by gianmaria** [comment] 2016-04-19 08:32
oh yesssss it worked out great! thank you!

**Comment by jfschmakeit** [comment] 2016-04-19 09:22
Let's keep it open until it's fixed in the repository. Ideally the samples here should 'just compile' straight from a clean check out. :-)

**Comment by jfschmakeit** [comment] 2016-04-19 09:22
@jguomoto  Could you take a look?

**Comment by jguomoto** [comment] 2016-04-25 17:26
@jfschmakeit @gianmaria thanks for catching the bug, we found it's related to different android studio version. It will get fixed in next release.

**Closed** 2016-08-12 16:36 UTC
